/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 07/02/2019 15:56:37
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            40000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            8000000
#define MX_HSE_VALUE                            8000000
#define MX_PLLCLKFreq_Value                     8000000
#define MX_SYSCLKFreq_VALUE                     8000000
#define MX_HCLKFreq_Value                       8000000
#define MX_HSIPLLFreq_Value                     4000000
#define MX_HSEPLLFreq_Value                     8000000
#define MX_MCOFreq_Value                        8000000
#define MX_CortexFreq_Value                     8000000
#define MX_AHBFreq_Value                        8000000
#define MX_APB1Freq_Value                       8000000
#define MX_APB2Freq_Value                       8000000
#define MX_APB1TimFreq_Value                    8000000
#define MX_APB2TimFreq_Value                    8000000
#define MX_I2C1Freq_Value                       8000000
#define MX_I2C2Freq_Value                       8000000
#define MX_USART1Freq_Value                     8000000
#define MX_USART2Freq_Value                     8000000
#define MX_USART3Freq_Value                     8000000
#define MX_RTCFreq_Value                        40000
#define MX_RTCHSEDivFreq_Value                  250000
#define MX_USBFreq_Value                        8000000
#define MX_WatchDogFreq_Value                   40000

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */
